# Site settings
title: Software Engineering Notes
description: A collection of software engineering topics explained with real-world examples
baseurl: "/software_engineering" # Subdirectory for your project
url: "https://nabilr.github.io" # Your GitHub Pages base URL


# Theme (Minimal Mistakes is an excellent choice for a sidebar)
remote_theme: "mmistakes/minimal-mistakes" 

# Navigation Sidebar (linking sections of your notes)
sidebar:
  nav: "software_engineering"



# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar: true
  - scope:
      path: ""
      type: notes
    values:
      layout: single
      sidebar: true

# Markdown Settings
markdown: kramdown
highlighter: rouge

# Data includes (sidebar navigation file)
include:
  - _data/navigation.yml
